apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    some-label: default
    namespace: default
spec:
  containers:
  - name: helm
    image: lachlanevenson/k8s-helm:v3.1.1
    command:
    - cat
    tty: true
  serviceAccountName: jenkins
